name: shop_flutter
description: MVP e-commerce
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # routing + state
  go_router: ^17.0.0
  provider: ^6.1.5+1        # ou riverpod si tu préfères

  # networking
  http: ^1.6.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1  # si besoin

  # share / platform
  share_plus: ^12.0.1

  # stripe (optionnel)
  flutter_stripe: ^12.1.1

  # UI helpers
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
