name: shop_flutter
description: MVP e-commerce
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # routing + state
  go_router: ^7.0.0
  provider: ^6.0.0        # ou riverpod si tu préfères

  # networking
  http: ^0.13.5

  # Firebase
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0  # si besoin

  # share / platform
  share_plus: ^6.3.0

  # stripe (optionnel)
  flutter_stripe: ^8.0.0

  # UI helpers
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
